package com.careerportal.service;

import com.careerportal.entity.*;
import com.careerportal.repository.CounselorNoteRepository;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * PDFService - generates professional PDF career reports
 */
@Service
public class PDFService {

    @Autowired
    private CounselorNoteRepository noteRepo;

    // PDF Fonts and Colors
    private static final BaseColor HEADER_COLOR = new BaseColor(63, 81, 181);  // Blue
    private static final BaseColor SECTION_COLOR = new BaseColor(103, 58, 183); // Purple
    private static final BaseColor LIGHT_GRAY = new BaseColor(245, 245, 245);

    /**
     * Generate a complete PDF career report for a student
     */
    public byte[] generateReport(Student student, AIReport report) throws DocumentException {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Document doc = new Document(PageSize.A4, 40, 40, 60, 40);
        PdfWriter.getInstance(doc, out);
        doc.open();

        // Fonts
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22, HEADER_COLOR);
        Font headingFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, SECTION_COLOR);
        Font labelFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11, BaseColor.BLACK);
        Font bodyFont = FontFactory.getFont(FontFactory.HELVETICA, 10, BaseColor.DARK_GRAY);
        Font smallFont = FontFactory.getFont(FontFactory.HELVETICA, 9, BaseColor.GRAY);

        // ---- HEADER ----
        addHeader(doc, titleFont, smallFont, student);

        // ---- STUDENT PROFILE ----
        addSection(doc, headingFont, labelFont, bodyFont, "Student Profile", buildProfileContent(student));

        // ---- AI ANALYSIS ----
        if (report != null) {
            addSection(doc, headingFont, labelFont, bodyFont, "AI Career Analysis", buildAIContent(report));
            addSection(doc, headingFont, labelFont, bodyFont, "Career Recommendations", buildRecommendationContent(report));
            addSection(doc, headingFont, labelFont, bodyFont, "Career Roadmap", report.getCareerRoadmap() != null ? report.getCareerRoadmap() : "Not available");
        }

        // ---- COUNSELOR NOTES ----
        List<CounselorNote> notes = noteRepo.findByStudentIdOrderByCreatedAtDesc(student.getId());
        if (!notes.isEmpty()) {
            StringBuilder noteContent = new StringBuilder();
            for (CounselorNote note : notes) {
                noteContent.append("• ").append(note.getNoteText()).append("\n");
            }
            addSection(doc, headingFont, labelFont, bodyFont, "Counselor Notes", noteContent.toString());
        }

        // Footer
        Paragraph footer = new Paragraph("\nGenerated by AI Career Portal | " +
                java.time.LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd MMM yyyy, hh:mm a")),
                smallFont);
        footer.setAlignment(Element.ALIGN_CENTER);
        doc.add(footer);

        doc.close();
        return out.toByteArray();
    }

    private void addHeader(Document doc, Font titleFont, Font smallFont, Student student) throws DocumentException {
        // Title banner
        PdfPTable banner = new PdfPTable(1);
        banner.setWidthPercentage(100);
        PdfPCell cell = new PdfPCell();
        cell.setBackgroundColor(HEADER_COLOR);
        cell.setPadding(15);
        cell.setBorder(Rectangle.NO_BORDER);

        Font whiteTitle = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20, BaseColor.WHITE);
        Font whiteSub = FontFactory.getFont(FontFactory.HELVETICA, 11, BaseColor.WHITE);
        Paragraph title = new Paragraph("🎓 AI Career Portal", whiteTitle);
        title.setAlignment(Element.ALIGN_CENTER);
        Paragraph sub = new Paragraph("Career Assessment Report", whiteSub);
        sub.setAlignment(Element.ALIGN_CENTER);
        cell.addElement(title);
        cell.addElement(sub);
        banner.addCell(cell);
        doc.add(banner);
        doc.add(Chunk.NEWLINE);
    }

    private void addSection(Document doc, Font headingFont, Font labelFont, Font bodyFont,
                            String title, String content) throws DocumentException {
        // Section heading
        PdfPTable header = new PdfPTable(1);
        header.setWidthPercentage(100);
        PdfPCell headerCell = new PdfPCell(new Phrase(title, headingFont));
        headerCell.setBackgroundColor(LIGHT_GRAY);
        headerCell.setPadding(8);
        headerCell.setBorderColor(SECTION_COLOR);
        header.addCell(headerCell);
        doc.add(header);

        // Content
        if (content != null && !content.isBlank()) {
            Paragraph p = new Paragraph(content, bodyFont);
            p.setIndentationLeft(10);
            p.setSpacingAfter(10);
            doc.add(p);
        }
        doc.add(Chunk.NEWLINE);
    }

    private String buildProfileContent(Student s) {
        return "Name: " + s.getUser().getFullName() + "\n" +
               "Email: " + s.getUser().getEmail() + "\n" +
               "School: " + (s.getSchool() != null ? s.getSchool() : "N/A") + "\n" +
               "Class: " + (s.getCurrentClass() != null ? s.getCurrentClass() : "N/A") + "\n" +
               "Board: " + (s.getBoard() != null ? s.getBoard() : "N/A") + "\n" +
               "Overall %: " + (s.getOverallPercentage() != null ? s.getOverallPercentage() + "%" : "N/A") + "\n" +
               "Skills: " + (s.getSkills() != null ? s.getSkills() : "N/A") + "\n" +
               "Interests: " + (s.getInterests() != null ? s.getInterests() : "N/A") + "\n" +
               "Career Goal: " + (s.getCareerGoal() != null ? s.getCareerGoal() : "N/A");
    }

    private String buildAIContent(AIReport r) {
        return "Personality: " + safe(r.getPersonality()) + "\n\n" +
               "Strengths: " + safe(r.getStrengths()) + "\n\n" +
               "Areas to Improve: " + safe(r.getWeaknesses()) + "\n\n" +
               "Career Match: " + safe(String.valueOf(r.getCareerMatchPercent())) + "%";
    }

    private String buildRecommendationContent(AIReport r) {
        return "Best Careers: " + safe(r.getBestCareers()) + "\n\n" +
               "Skills to Learn: " + safe(r.getSkillsToLearn()) + "\n\n" +
               "Certifications: " + safe(r.getCertifications()) + "\n\n" +
               "Recommended Courses: " + safe(r.getRecommendedCourses()) + "\n\n" +
               "Jobs: " + safe(r.getRecommendedJobs()) + "\n\n" +
               "Internships: " + safe(r.getInternshipSuggestions());
    }

    private String safe(String s) {
        return s != null ? s : "N/A";
    }
}
